"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var user_1 = require("./user");
var services_1 = require("./services");
var order_1 = require("./order");
user_1.default.hasMany(services_1.default, { foreignKey: 'userId' });
services_1.default.belongsTo(user_1.default, { foreignKey: 'userId' });
services_1.default.hasMany(order_1.default, { foreignKey: 'serviceId' });
order_1.default.belongsTo(services_1.default, { foreignKey: 'serviceId' });
user_1.default.hasMany(order_1.default, { foreignKey: 'userId' });
order_1.default.belongsTo(user_1.default, { foreignKey: 'userId' });
