import { Model, DataTypes, Optional } from 'sequelize';
import { sequelize } from '../config/database';  // Import the sequelize instance from your database config

// Define the attributes for the Service model
interface ServiceAttributes {
  id: number;
  title: string;
  description: string;
  price: number;
  name: string;
  userId: number;  // Foreign key for the User model
}

// Define the optional attributes for creation (since id will be generated by the database)
interface ServiceCreationAttributes extends Optional<ServiceAttributes, 'id'> {}

// Define the Service model using Sequelize
class Service extends Model<ServiceAttributes, ServiceCreationAttributes> implements ServiceAttributes {
  public id!: number;
  public title!: string;
  public description!: string;
  public price!: number;
  public name!: string;
  public userId!: number;

  // Timestamps
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

// Initialize the Service model
Service.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    price: {
      type: DataTypes.FLOAT,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  },
  {
    sequelize, // Pass in the Sequelize instance
    modelName: 'Service',
    tableName: 'services', // The table name in the database
  }
);

export default Service;
