import { Model, DataTypes, Optional } from 'sequelize';  // Import Sequelize types
import { sequelize } from '../config/database';            // Import the initialized Sequelize instance

// Define the attributes for the Service model
interface ServiceAttributes {
  id: number;
  userId: number;
  title: string;
  description: string;
  price: number;
  name: string;  // Add name property
}

// Define the creation attributes (without `id` as it's auto-generated by Sequelize)
interface ServiceCreationAttributes extends Optional<ServiceAttributes, 'id'> {}

// Define the Service model class
class Service extends Model<ServiceAttributes, ServiceCreationAttributes> implements ServiceAttributes {
  public id!: number;
  public userId!: number;
  public title!: string;
  public description!: string;
  public price!: number;
  public name!: string;  // Add name property to the model class

  // You can add additional instance methods here if needed
}

// Initialize the model
Service.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,   // Mark the 'id' as primary key
      allowNull: false,   // Ensure 'id' cannot be null
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,   // 'userId' cannot be null
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,   // 'title' cannot be null
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false,   // 'description' cannot be null
    },
    price: {
      type: DataTypes.FLOAT,
      allowNull: false,   // 'price' cannot be null
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,   // 'name' cannot be null
    },
  },
  {
    sequelize,           // Pass the Sequelize instance
    modelName: 'Service',
    tableName: 'services', // Ensure the table name matches
    timestamps: true,    // Enable automatic timestamps (createdAt, updatedAt)
  }
);

export default Service;
export { ServiceCreationAttributes };
