import { Model, DataTypes, Optional } from 'sequelize';
import { sequelize } from '../config/database'; // Ensure this is a named import if you're using named exports

// Define the attributes for the Service model
interface ServiceAttributes {
  id: number;
  userId: number;
  title: string;
  description: string;
  price: number;
}

// Define the creation attributes (without `id` as it's auto-generated by Sequelize)
interface ServiceCreationAttributes extends Optional<ServiceAttributes, 'id'> {}

// Define the Service model class
class Service extends Model<ServiceAttributes, ServiceCreationAttributes> implements ServiceAttributes {
  public id!: number;
  public userId!: number;
  public title!: string;
  public description!: string;
  public price!: number;

  // You can also add additional model methods here if needed
}

// Initialize the model
Service.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true, // Mark the 'id' as primary key
      allowNull: false, // Ensure 'id' cannot be null
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    price: {
      type: DataTypes.FLOAT,
      allowNull: false,
    },
  },
  {
    sequelize, // Make sure sequelize instance is passed here
    modelName: 'Service',
  }
);

export default Service;
export { ServiceCreationAttributes };
