import { DataTypes, Model, Optional } from 'sequelize';
import { sequelize } from '../config/database'; // Use named import for sequelize

// Define the UserAttributes interface
export interface UserAttributes {
  id?: number; // Optional because Sequelize auto-generates the ID
  username: string;
  email: string;
  password: string;
  firstName?: string | null; // Allow null for optional fields
  lastName?: string | null;
  role: string;
  subscriptionStatus: string;
  createdAt?: Date | null; // Auto-generated by Sequelize
  updatedAt?: Date | null; // Auto-generated by Sequelize
}

// Define the UserCreationAttributes interface for creating a user without an ID
export interface UserCreationAttributes extends Optional<UserAttributes, 'id'> {}

// Define the User model class
class User
  extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes
{
  public id!: number;
  public username!: string;
  public email!: string;
  public password!: string;
  public firstName!: string | null;
  public lastName!: string | null;
  public role!: string;
  public subscriptionStatus!: string;
  public createdAt!: Date | null;
  public updatedAt!: Date | null;

  // Define associations (if needed)
  static associate(models: any) {
    // Add associations here if applicable, e.g., User.hasMany(models.Post);
  }
}

// Initialize the User model
User.init(
  {
    username: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true, // Ensure the username is unique
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true, // Ensure the email is unique
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    firstName: {
      type: DataTypes.STRING,
      allowNull: true, // Allow null for firstName
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: true, // Allow null for lastName
    },
    role: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: 'Free', // Default role to 'Free'
    },
    subscriptionStatus: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: 'Inactive', // Default subscription status to 'Inactive'
    },
  },
  {
    sequelize, // Pass the sequelize instance
    tableName: 'users', // Specify the table name
    timestamps: true, // Enable Sequelize to handle createdAt and updatedAt
    createdAt: 'createdAt', // Map Sequelize's createdAt to 'createdAt' column
    updatedAt: 'updatedAt', // Map Sequelize's updatedAt to 'updatedAt' column
  }
);

export default User;
